-- Gold API market storage: append-only samples plus one source-owned M15 candle per UTC bucket.
-- This migration is forward-only. Do not reset, truncate, or rewrite existing tables.

CREATE TABLE IF NOT EXISTS public.market_price_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL DEFAULT 'gold-api-xau-eur',
  version text NOT NULL DEFAULT '1.0.0',
  symbol text NOT NULL DEFAULT 'XAUEUR',
  currency text NOT NULL DEFAULT 'EUR',
  price numeric(20, 8) NOT NULL CHECK (price > 0),
  provider_updated_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_price_samples_source_contract CHECK (
    source = 'gold-api-xau-eur'
    AND version = '1.0.0'
    AND symbol = 'XAUEUR'
    AND currency = 'EUR'
  ),
  CONSTRAINT market_price_samples_idempotency_key
    UNIQUE (source, version, symbol, provider_updated_at)
);

CREATE INDEX IF NOT EXISTS market_price_samples_updated_idx
  ON public.market_price_samples (source, version, symbol, provider_updated_at DESC);

CREATE OR REPLACE FUNCTION public.enforce_market_sample_append_only()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'market price samples are append-only';
END;
$$;

DROP TRIGGER IF EXISTS market_price_samples_append_only ON public.market_price_samples;
CREATE TRIGGER market_price_samples_append_only
  BEFORE UPDATE OR DELETE ON public.market_price_samples
  FOR EACH ROW EXECUTE FUNCTION public.enforce_market_sample_append_only();

CREATE TABLE IF NOT EXISTS public.market_candles (
  source text NOT NULL DEFAULT 'gold-api-xau-eur',
  version text NOT NULL DEFAULT '1.0.0',
  symbol text NOT NULL DEFAULT 'XAUEUR',
  timeframe text NOT NULL DEFAULT 'M15',
  bucket_start timestamptz NOT NULL,
  open numeric(20, 8) NOT NULL CHECK (open > 0),
  high numeric(20, 8) NOT NULL CHECK (high >= open AND high >= close),
  low numeric(20, 8) NOT NULL CHECK (low <= open AND low <= close),
  close numeric(20, 8) NOT NULL CHECK (close > 0),
  first_sample_at timestamptz NOT NULL,
  last_sample_at timestamptz NOT NULL,
  sample_count integer NOT NULL CHECK (sample_count > 0),
  is_closed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source, version, symbol, timeframe, bucket_start),
  CONSTRAINT market_candles_source_contract CHECK (
    source = 'gold-api-xau-eur'
    AND version = '1.0.0'
    AND symbol = 'XAUEUR'
    AND timeframe = 'M15'
  ),
  CONSTRAINT market_candles_utc_bucket CHECK (
    bucket_start = date_trunc('minute', bucket_start AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
    AND extract(minute FROM bucket_start AT TIME ZONE 'UTC') IN (0, 15, 30, 45)
  ),
  CONSTRAINT market_candles_sample_order CHECK (first_sample_at <= last_sample_at)
);

CREATE INDEX IF NOT EXISTS market_candles_closed_bucket_idx
  ON public.market_candles (source, version, symbol, timeframe, is_closed, bucket_start DESC);

CREATE OR REPLACE FUNCTION public.enforce_market_candle_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.is_closed AND (
    NEW.source IS DISTINCT FROM OLD.source
    OR NEW.version IS DISTINCT FROM OLD.version
    OR NEW.symbol IS DISTINCT FROM OLD.symbol
    OR NEW.timeframe IS DISTINCT FROM OLD.timeframe
    OR NEW.bucket_start IS DISTINCT FROM OLD.bucket_start
    OR NEW.open IS DISTINCT FROM OLD.open
    OR NEW.high IS DISTINCT FROM OLD.high
    OR NEW.low IS DISTINCT FROM OLD.low
    OR NEW.close IS DISTINCT FROM OLD.close
    OR NEW.first_sample_at IS DISTINCT FROM OLD.first_sample_at
    OR NEW.last_sample_at IS DISTINCT FROM OLD.last_sample_at
    OR NEW.sample_count IS DISTINCT FROM OLD.sample_count
    OR NEW.is_closed IS DISTINCT FROM OLD.is_closed
    OR NEW.created_at IS DISTINCT FROM OLD.created_at
    OR NEW.updated_at IS DISTINCT FROM OLD.updated_at
  ) THEN
    RAISE EXCEPTION 'closed market candle is immutable';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS market_candles_lock_after_close ON public.market_candles;
CREATE TRIGGER market_candles_lock_after_close
  BEFORE UPDATE ON public.market_candles
  FOR EACH ROW EXECUTE FUNCTION public.enforce_market_candle_immutability();

ALTER TABLE public.market_price_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_candles ENABLE ROW LEVEL SECURITY;

-- No browser role can write or read the raw market store directly. The app reads
-- closed candles through a server-only function, while the Edge Function writes
-- through the SECURITY DEFINER RPC below.
REVOKE ALL ON TABLE public.market_price_samples FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.market_candles FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.market_price_samples TO service_role;
GRANT ALL ON TABLE public.market_candles TO service_role;

CREATE OR REPLACE FUNCTION public.ingest_gold_api_price(
  p_price numeric,
  p_updated_at timestamptz,
  p_ingested_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sample_inserted boolean;
  v_sample_rows integer;
  v_bucket_start timestamptz;
  v_candle record;
BEGIN
  IF p_price IS NULL OR p_price <= 0 OR p_price = 'NaN'::numeric THEN
    RAISE EXCEPTION 'Gold API price must be a positive finite number';
  END IF;
  IF p_updated_at IS NULL THEN
    RAISE EXCEPTION 'Gold API updatedAt is required';
  END IF;
  IF p_ingested_at IS NULL OR p_ingested_at > now() + interval '2 minutes' THEN
    RAISE EXCEPTION 'ingested_at is invalid or too far in the future';
  END IF;
  IF p_updated_at > p_ingested_at + interval '1 minute' THEN
    RAISE EXCEPTION 'provider timestamp is too far in the future';
  END IF;

  -- Derive the bucket in UTC regardless of the database session timezone.
  v_bucket_start := (
    date_trunc('hour', p_updated_at AT TIME ZONE 'UTC')
    + floor(extract(minute FROM p_updated_at AT TIME ZONE 'UTC') / 15)::integer * interval '15 minutes'
  ) AT TIME ZONE 'UTC';

  INSERT INTO public.market_price_samples (
    source, version, symbol, currency, price, provider_updated_at, ingested_at
  ) VALUES (
    'gold-api-xau-eur', '1.0.0', 'XAUEUR', 'EUR', p_price, p_updated_at, p_ingested_at
  )
  ON CONFLICT (source, version, symbol, provider_updated_at) DO NOTHING;

  GET DIAGNOSTICS v_sample_rows = ROW_COUNT;
  v_sample_inserted := v_sample_rows > 0;

  -- A repeated provider timestamp is a no-op. This prevents a cached response
  -- from inflating sample_count or moving close to a duplicate price.
  IF v_sample_inserted THEN
    INSERT INTO public.market_candles (
      source, version, symbol, timeframe, bucket_start,
      open, high, low, close, first_sample_at, last_sample_at, sample_count, is_closed
    ) VALUES (
      'gold-api-xau-eur', '1.0.0', 'XAUEUR', 'M15', v_bucket_start,
      p_price, p_price, p_price, p_price, p_updated_at, p_updated_at, 1,
      v_bucket_start + interval '15 minutes' <= p_ingested_at
    )
    ON CONFLICT (source, version, symbol, timeframe, bucket_start) DO UPDATE SET
      open = CASE
        WHEN EXCLUDED.first_sample_at < market_candles.first_sample_at THEN EXCLUDED.open
        ELSE market_candles.open
      END,
      high = GREATEST(market_candles.high, EXCLUDED.high),
      low = LEAST(market_candles.low, EXCLUDED.low),
      close = CASE
        WHEN EXCLUDED.last_sample_at >= market_candles.last_sample_at THEN EXCLUDED.close
        ELSE market_candles.close
      END,
      first_sample_at = LEAST(market_candles.first_sample_at, EXCLUDED.first_sample_at),
      last_sample_at = GREATEST(market_candles.last_sample_at, EXCLUDED.last_sample_at),
      sample_count = market_candles.sample_count + 1,
      is_closed = market_candles.is_closed
        OR EXCLUDED.bucket_start + interval '15 minutes' <= p_ingested_at,
      updated_at = now()
    WHERE NOT market_candles.is_closed;
  END IF;

  -- Closing changes only the lifecycle flag. OHLC values in a closed candle are
  -- never modified by later calls, preserving closed-candle immutability.
  UPDATE public.market_candles
  SET is_closed = true, updated_at = now()
  WHERE source = 'gold-api-xau-eur'
    AND version = '1.0.0'
    AND symbol = 'XAUEUR'
    AND timeframe = 'M15'
    AND NOT is_closed
    AND bucket_start + interval '15 minutes' <= p_ingested_at;

  SELECT c.* INTO v_candle
  FROM public.market_candles AS c
  WHERE c.source = 'gold-api-xau-eur'
    AND c.version = '1.0.0'
    AND c.symbol = 'XAUEUR'
    AND c.timeframe = 'M15'
    AND c.bucket_start = v_bucket_start;

  RETURN jsonb_build_object(
    'sampleInserted', v_sample_inserted,
    'bucketStart', v_bucket_start,
    'candleClosed', COALESCE(v_candle.is_closed, false),
    'sampleCount', COALESCE(v_candle.sample_count, 0),
    'source', 'gold-api-xau-eur',
    'version', '1.0.0'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.ingest_gold_api_price(numeric, timestamptz, timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ingest_gold_api_price(numeric, timestamptz, timestamptz)
  TO service_role;