-- Compatibility marker (intentionally no-op).
--
-- The canonical Phase 0 ownership/RLS migration is
-- 20260827063617_96cb8d49-e44f-4959-90d4-31cbe3e9cab6.sql. It already
-- contains every change that was duplicated in this migration, plus the
-- settled-result immutability trigger. Keeping this timestamp as a no-op lets
-- existing migration histories remain comparable while preventing duplicate
-- CREATE POLICY statements from failing on a fresh Supabase project.
